Sun Aug 19 22:25:12 CST 2018 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: No se ha encontrado la base de datos '.\DB\Derby.DB'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at Controlador.Conexion.AccederBD(Conexion.java:53)
	at Vista.VPrincipal.<init>(VPrincipal.java:19)
	at orion_proyect.Orion_Proyect.main(Orion_Proyect.java:18)
Caused by: java.sql.SQLException: No se ha encontrado la base de datos '.\DB\Derby.DB'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 17 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: No se ha encontrado la base de datos '.\DB\Derby.DB'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at Controlador.Conexion.AccederBD(Conexion.java:53)
	at Vista.VPrincipal.<init>(VPrincipal.java:19)
	at orion_proyect.Orion_Proyect.main(Orion_Proyect.java:18)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Sun Aug 19 22:25:19 CST 2018:
 Iniciando instancia a816c00e-0165-5594-631c-00000598c008 de Derby, versi√≥n The Apache Software Foundation - Apache Derby - 10.10.2.0 - (1582446): 
en el directorio de base de datos C:\Users\Christian\Desktop\Pagina Progra\Proyecto_Leonardo_Kailor_Vinicio\Proyecto1.1\DB\Derby.DB con el cargador de clases sun.misc.Launcher$AppClassLoader@4e0e2f2a
Cargado desde file:/C:/Program%20Files/glassfish-4.1.1/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_65-b17
user.dir=C:\Users\Christian\Desktop\Pagina Progra\Proyecto_Leonardo_Kailor_Vinicio\Proyecto1.1
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=null
Cargador de clases de base de datos iniciado - derby.database.classpath=''
